dist: trusty
jdk: oraclejdk8

language: java

sudo: false

install: true

script: .infra/mvn_sonar.sh

branches:
  only:
    - master
    - v3
    - v4

cache:
  directories:
  - "$HOME/.m2/repository"
